### ISSUE TITLE
Entrümpeln

### ISSUE THREAD

**Issue by Jeinzi** [Wohnwagen/management#11]
Egal was jetzt mit dem Wohnwagen passiert - wir müssen ihn so oder so entrümpeln. Sollten uns also in aller Bälde treffen und schauen, was sofort weg kann, und aus was man vielleicht noch ein paar Euros rausbekommen könnte.

**Comment by glowGrape** [comment]
bidde!
Ich kann heute mittags und morgen abend, call me maybe

**Comment by FridolinAmadeus** [comment]
Lieber morgen Abend. Ich muss mir noch die Hornhaut von meinen Fußsohlen raspeln.
