### ISSUE TITLE
Vorbereiten des Geländes für die Wohnwagenanlieferung

### ISSUE THREAD

**Issue by Jintzo** [Wohnwagen/management#4]
Damit der Wohnwagen geliefert und direkt an seinen dauerhaften Platz gebracht werden kann, muss das Gelände entsprechend vorbereitet werden:

- [x] Gelände besichtigen
- [x] hohes Gras entfernen
- [ ] Boden plattmachen
- [ ] Boden befestigen

-----
Angesetzt ist dafür vorerst **Donnerstagmorgen**, siehe *Google Calendar*.
Sobald das gemacht ist, sollte man den Wohnwagen dauerhaft platzieren können. Das muss im krassesten Fall bis ca. **Samstagmittag** gemacht sein! :fearful: :smile:

**Comment by Jeinzi** [comment]
Der einzuebnende Bereich ist jetzt abgesteckt. Hütte und Baum werden ausgespart, als angestrebtes Niveau wurde der quasi niedrigste Punkt rechts ausgewählt (alle Angaben hangabwärtsschauend).
Da das Gelände sowohl nach links als auch nach vorne abfällt, können wir das Material von rechts nach links umschichten und sollten eine einigermaßen ebene Fläche erhalten.
