### ISSUE TITLE
Material für die Grundstücksvorbereitung

### ISSUE THREAD

**Issue by Jintzo** [Wohnwagen/management#5]
Um das Grundstück wie in #4 beschrieben vorbereiten zu können brauchen wir ein bisschen Kram:

* **Werkzeug, um hohes Gras zu entfernen** (hier hilft ein Rasenmäher vermutlich nur begrenzt weiter, zuerst muss das hohe Gras anderweitig entfernt werden) - hat jemand eine **Sichel** oder etwas ähnliches? **@Johanna**: ist vielleicht in dem Schuppen eine?
* **Werkzeug, um Boden platt zu machen** (Bodenfräse hat glaube ich @Jeinzi, ansonsten wären ein paar Schaufeln und eine Schubkarre sicher sehr praktisch. Auch hier könnte vielleicht schon was im Schuppen sein.)
* **Sachen, um den Untergrund gerade zu machen** (ich habe eine lange Wasserwaage, vielleicht kennt sich ja jemand aus und weiß was besseres?)

* **Material, um den Untergrund stabil zu machen** (ich glaube, wir haben hier noch Steinplatten, ich gucke bei Gelegenheit mal nach, vielleicht hat ja noch jemand von euch welche)

----

Wer was hat bitte hier melden!

**Comment by johanna** [comment]
Hello! I think you got the wrong Johanna. I'm however now very curious
about your project. What is the caravan for? And why did you choose github
to host the project management on (what seems to be) a non-code-project?

Best regards,
Johanna Eriksson

2015-06-03 0:22 GMT+02:00 Jintzo <notifications@github.com>:

**Comment by Jeinzi** [comment]
@johanna Thats interesting to see who ends up on this site :smiley: 

Well, we're altogether ten students and we know each other for quite a long time. A few days back we bought an old and unroadworthy caravan and we got a piece of land from one of our grandparants where we may put it. Our plan is to renovate it so we can relax there and celebrate New Year's Eve and maybe add a small garden, we got many ideas :smile:

Why Github: We know it from other coding projects - at least @Jintzo, @GlowGrape and me - and we liked the easy way of tracking issues, tagging them, creating a small wiki and a website etc. It's mainly a non-code-project, but we have the idea to connect it to the internet (e.g. displaying if someone is in there, plotting weather data), so I think there will be several coding projects. And finally, we think it's very intuitive to use for the other people in our team.

Greetings from Germany!

**Comment by Jeinzi** [comment]
Ich bringe:
- Rasenmäher
- Bodenfräse
- Trimmer

Wie auch immer
man das transportiert.

**Comment by Jintzo** [comment]
Hi @johanna!

I didn't meant to tag you in my comment - that was automagically done by Github :worried:

Sorry!

**Comment by johanna** [comment]
Thanks for the answer and good luck with the caravan!

/Johanna

**Comment by glowGrape** [comment]
Für unter den Wohnwagen haben wir stabile Waschbetonplatten, ausreichend viele
