### ISSUE TITLE
Sicherheitssystem

### ISSUE THREAD

**Issue by Jeinzi** [Wohnwagen/management#7]
Um den Wohnwagen im Ernstfall vor Eindringlingen zu schützen, sollten eventuell ein oder mehrere laute bzw. helle Gefrickel zur Abschreckung verbaut werden, die aktiviert werden, sobald sich jemand unautorisierten Zutritt verschafft.

Vorschläge:
- Bewegungsmelder mit Lampe.
- Lichtschranke am Eingang, mit einem Mikrocontroller und weiterem Gefrickel gekoppelt.

Weitere Ideen gesucht!

**Comment by Jintzo** [comment]
Hört sich gut an! Dafür brauchen wir aber Strom und im besten Fall Netzwerk im Wohnwagen, kriegen wir das hin?

**Comment by glowGrape** [comment]
Wir haben keinen Schlüssel zum Wohnwagen, meines Wissens nach.
Also neues Schloss frickeln
