### ISSUE TITLE
Wasser und Strom

### ISSUE THREAD

**Issue by Jintzo** [Wohnwagen/management#8]
Haben wir auf dem Gelände

- [ ] Wasser

- [ ] Strom ?

**Comment by Jintzo** [comment]
Update: Wir haben weder Wasser noch Strom. Da müssen wir vielleicht mal was organisieren...

**Comment by Jeinzi** [comment]
Wasser lässt sich ja teilweise durch Regenwasser ersetzen - also Regentonnen organisieren!

**Comment by Jintzo** [comment]
Bei Strom gibt es ja im Prinzip zwei Möglichkeiten:

* selber erzeugen: Generator, Windräder, Solarplatten, ...

* nicht selber erzeugen: da sollten wir vielleicht mal die Nachbarn fragen, wie die ihren Strom beziehen. Problem dabei sind natürlich eventuell (oder eher sicher!) entstehende Kosten.

**Comment by Jintzo** [comment]
ofa

**Comment by Jeinzi** [comment]
Es kam auch schon die Idee auf einen Wasser- bzw. Stromzähler zwischen uns und den Nachbarn einzubauen. Dann brauchen wir keinen eigenen Anschluss und können denen das einfach zahlen.

**Comment by Jintzo** [comment]
Gerne, wenn die da mitmachen :laughing:

**Comment by glowGrape** [comment]
Ich hätte Lust, mal eine Biogasanlage zu frickeln.
Das ist vom Prinzip her nicht so schwer und löst gleichzeitig unser Toilettenproblem.
https://www.youtube.com/watch?v=QuDhuYDL0Yw
Etwas in der Art.

**Comment by Jeinzi** [comment]
Ich glaube vor dem Stall nebenan sind einige regentonnenartige Gebilde. Ich schau mir die Tage mal an, was man davon gebrauchen kann.
